name: Build&Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: swift test -v --enable-code-coverage
    - name: Prepare Code Coverage
      run: xcrun llvm-cov export -format="lcov" .build/debug/TraktKitPackageTests.xctest/Contents/MacOS/TraktKitPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
